### ISSUE TITLE
Logout / Token expire

### ISSUE THREAD

**Issue by vip9** [olivierandriessen/phalcon-rest#20]
Hello,
is there any way to give ability to /users/logout? Or make token expired faster?

**Comment by fili28** [comment]
Hi,
token is stored only on client side, so you can't change the token you already sent to client from server side. This means you can logout user only by deleting the token from client side. To make token expire faster, you would have to decode the Jason Web token (all information like id, expiration date etc. are stored in it), change date and encode the data back, but this is not possible, because you don't know secret from server side. Hope it helps and sorry for my english.

**Comment by vip9** [comment]
I was thinking more like "blacklisting" tokens to force-login.

**Comment by andevsoftware** [comment]
@fili28, @vip9 You are right. In order to logout you simply delete the token client side. You could also keep the tokens inside the database and authenticate against that. By doing that you can block users when specific tokens are blacklisted.

**Comment by andevsoftware** [comment]
@vip9 I will close this issue since this is a specific use case and will differ per application. This library provides the most straightforward setup as a starting point for the developer.
